### ISSUE TITLE
Bug: chart not re-rendering when `TooltipGuide`'s `renderer` changes

### ISSUE THREAD

**Issue by bernardobelchior** [entronad/graphic#100]
By default, in graphic, a chart re-renders when the new spec is different from the previous spec. This comparison is done in the [`equalSpecTo`](https://github.com/entronad/graphic/blob/a8747b51bf2678c7873cb5009dca3566b490aa62/lib/src/chart/chart.dart#L159) function. This compares a subset of all properties, including the `tooltip` property.

The `tooltip` property is a `TooltipGuide` and has its own [`==` operator override](https://github.com/entronad/graphic/blob/1341d99752d6ebb033db720cbc0c194cefd256c0/lib/src/guide/interaction/tooltip.dart#L163-L179). As you can see, that override does not compare the `renderer` property. 

This results in the chart not being updating when the `renderer` property changes. 

@entronad do you have any ideas on how to fix this? The simple solution would be to compare the `renderer` property, but I'm assuming this was left out on purpose. Would it make more sense to add a `rendererKey` that would be compared in order to re-render the chart?

Thanks for the support!

**Comment by entronad** [comment]
That is on purpose. Because `renderer` property's type is function. any property that is a function will not be compared in `eqaulSpecTo` and regarded equal to the old one.

The reason is most people like to write chart definitions in literals, including function properties:
```
Chart(
  ...
  renderer: (value) => value.toString(),
)
```

So in each build() method, these properties are different instances. That is why classes used in spec have to override `==` operators to check they are really "equal". But functions can not override `==`, different instances will always regarded not `==`.

The auto compare of equalSpecTo is a assistant way to reduce rerenderrings. But for function properties it will not work. (I will add this tip to documents ).

The solution is to use `Chart.rebuild`. Set it `true` to make it always rebuild. If you know when your function property is changed, you can write some judgement outside the spec to control the `Chart.rebuild`, which will reduce redundant rebuildings.
