### ISSUE TITLE
[Feature Request] Paint `Tooltip` on top of elements outside `Chart`

### ISSUE THREAD

**Issue by bernardobelchior** [entronad/graphic#112]
Hey, there!

I have a use case where `graphic`'s `Tooltip` should be painted on top of elements that do not belong to a chart. 

See the example below:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/12778398/170281832-731b594d-6ecd-4cb3-9ba6-1f83cf683c43.png">

<img width="726" alt="image" src="https://user-images.githubusercontent.com/12778398/170282129-b0657a01-b997-439c-8622-1f8237171c62.png">

The tooltip should render on top of the "Chart over limits" horizontal bar. Unfortunately, that bar cannot be rendered under the chart, since it should be floating and render on top of the chart, as you can see in the second image.

I'd like to add a way of rendering the tooltip above that bar, possibly using an `Overlay`. I'm opening this issue because I'd like to know:
1. If there's any way to do this in graphic at the moment, and;
2. If not, what would be the best way to implement that in graphic. I'd be willing to make a pull request to speed up the implementation.

Thank you!

**Comment by entronad** [comment]
You mean that you need to 'insert' a widget which zIndex layer is between the chart's elements and tooltips. That indeed needs some efforts because the `layer` property only works inside the chart and only works for chart components.
I imagine there are two ways:
1. If the 'chart over limits' widget is simple, you can implement it with Graphic's `CustomAnnotation`, then you can set its `layer` between the elements and tooltips.
2. You can build a chart without tooltip and the 'chart over limits' widget over it. The chart tooltip is in fact triggered by selections, so set the chart element's `selectionChannel` to be informed when some tuples are selected, use their indexes and the original data to build a tooltip widget on the very top.

**Comment by bernardobelchior** [comment]
Thank you, @entronad! The second option did solve my issue 🙏
