### ISSUE TITLE
When I set inflate: true, the PointElmenet is clipped

### ISSUE THREAD

**Issue by muuyao** [entronad/graphic#135]
When I set inflate: true, the PointElmenet is clipped

<img width="242" alt="image" src="https://user-images.githubusercontent.com/5389932/184563975-7bd19548-aea7-4d3f-9407-747259937b55.png">

I'd like to know how to avoid this problem

Thanks！

**Comment by entronad** [comment]
There is a padding between the chart coordinate region and the chart widget border, just like CSS.
The graphics overflow the widget border will be clipped while in overflow the coordinate region but in  the padding will not.
So you can set a small padding for the edge points.

**Comment by muuyao** [comment]
```dart
Chart(
      padding: (size) {
        return EdgeInsets.all(10);
      },
)
```
I set like this but it doesn't work

**Comment by entronad** [comment]
Sorry I misremembered.
The coord region has to clip the element graphics, because when you scale the coord, you only want to show part of the graphics in the coord region.

For your case, you can set a little space for the coord range:
```
coord: RectCoord(horizontalRange: [0.01, 0.99]),
```
See details in: https://pub.dev/documentation/graphic/latest/graphic/RectCoord/horizontalRange.html

**Comment by muuyao** [comment]
That did work, thanks
