### ISSUE TITLE
Scale one variable based on another variable

### ISSUE THREAD

**Issue by robnorr** [entronad/graphic#138]
Hi,

I want to show a line graph which shows two lines, updated by incoming data. Both lines share a Time variable for the x-axis. At first I thought I could solve it by having both Variables share an Element, using something like `position: Varset('Time') * (Varset('Variable1') + Varset('Variable2'))`, but this doesn't seem to be the way to do it (in fact this breaks an assertion of the variable's scales not being identical). So instead, I have separate Elements for each Variable. However, since the y-axis seems to only use the first Element in the list to create the y-axis, this leads to results like shown:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/59142770/185503095-6166f16d-c79f-481b-9c12-a87a55088d4e.png">
Note here, Variable1 (blue) data is [1, 0, 2, 4, 6]; Variable2 (green) data is [2, 2, 13, 14, 16]. So, because each variable is scaled based only on its _own_ maximum value, and the y-axis only uses the first element to create the labels, the resulting graph has a mismatch between the values of Variable2 and the y-axis.

I think a solution for this could be the the scales of each variable can use the global maximum value, by somehow accessing the other variable's data. Is this possible somehow?

Any help is much appreciated, please let me know if the question is unclear.

**Comment by robnorr** [comment]
For now, I have managed this by using 
`max(data1.reduce(max), data2.reduce(max))` in the `max` field of the LinearScale for both Variables. But I don't really like this as a solution, especially if I start scaling up to more a dozen lines on a single graph, so I'm still hoping there is a more dynamic/automatic solution possible

**Comment by entronad** [comment]
The default max and min setting is only for convenience in simple situations, there is no magic under the hood: it will iterator all the data and find the max and min one. So in fact it is not encouraged, for when there is numerous data it will harm the performance.

When multiple variables(with variable scales) show in one dim of the coord, the scales have different range is very common, in fact in most cases the variables indicate to different type of real-world values (and even be discrete), the case that they are the same type and have same range is rare.

So based on the reasons above, you may understand there is no automatic "normalization"(I think this is what you want me to do) for scales, and we encourage developers to manage the scales themselves, because they know their data best.

So if I am asked to normalize the two scales in your case, I will do the same as you: to iterate each data list and then find the bigger one. But it may not be the best way in other cases, so I didn't integrate it inside the lib as default.
