### ISSUE TITLE
Add draggable selection option

### ISSUE THREAD

**Issue by LucaCras** [entronad/graphic#160]
Add a new selection option where the selection changes by dragging the current selection.

**Comment by entronad** [comment]
The interval selection is draggable now, you mean you want an option to switch off it?

**Comment by LucaCras** [comment]
I mean a point selection that is draggable (i.e. a persistent point selection where selection only changes if pointer start location was last selection location)

**Comment by entronad** [comment]
If you set the selection gesture to PanUpdate, it will feels like you are dragging the point.

If you want only "draggable" when your finger start on the prior point selector, I think a Interval selector should be used. because in this system (it's the same as Vega), interval selector implies there is a "selector" you can control with your finger, while point selector implies there is no concrete "selector", you can only point a position.
