### ISSUE TITLE
About the changes of terminology and custom drawings

### ISSUE THREAD

**Issue by jhewitt** [entronad/graphic#210]
There is no mention in the change notes about what happened to the elements: property in the Chart class.  It now requires a marks: property as well which does not appear to accept the array of LineElement(s) that the elements: property accepted.

Is there any documentation describing these changes?

**Comment by gregwoodio** [comment]
I think the only documentation we're likely to get was:
```
Update terminology, some class names have changed:

GeomElement -> Mark

Attr -> Encode

Signal -> Event

Channel -> Stream

Figure -> MarkElement
```

So you'll need to rename your ```LineElements``` to ```LineMark```, and pass them to ```Chart```'s ```mark``` property instead of ```element```. That's all that was required to get our graphs up to date, aside from a bunch of changes to the way tooltips are drawn, which I'm still working through.

**Comment by entronad** [comment]
@jhewitt 
What @gregwoodio said is right, all terms, not only the class names are changed, I shall make clear of it in the changelog later. 

That is to say: `elements: [LineElement()]` is `marks: [LineMark()]`.

You can execute replaceing of all "element" to "mark" and "Element" to "Mark". The same to all other terms like "Attr", "Signal", and "Channel".

**Comment by gregwoodio** [comment]
Will there be an explanation of the changes to ```TooltipGuide```? It seems to require more changes than renaming ```PathFigure``` to ```PathElement```. Previously it accepted standard ```dart:ui``` paths, but now seems to require analogous ```Segments```, some of which are missing (RRect?)

**Comment by entronad** [comment]
@gregwoodio 
It seems you used custom renderer in the tooltips, thanks for that.

In the previous version, There is no animation in Graphic, so the rendering engine only need simple imperative path drawing, which is in `Figure` class.

But when we consider adding animations, a rendering engine that can resolve, store, and interpolate path commands is a must. So we made a totally new rendering engine and the usage of it is a little bit changed. Users that implemented custom shapes or tooltips need to make some changes.

The changes are easy to learn because the API is very similar to all other famous rendering engines. In a simple word, the path commands like `path.addRect` become objects like `RectElement` added to the scene.

I will write an article later. Now you can get some details from the example app and docs.

As to your case. You can use a RectElement which corner radius can be set (seperating Rect and RRect seems verbose). Only complex shapes need PathElement which is defined by custom Segments. The element types are in this dir: https://github.com/entronad/graphic/tree/main/lib/src/graffiti/element

**Comment by gregwoodio** [comment]
@entronad thank you! I'll try this out.

**Comment by entronad** [comment]
As pointed out in https://github.com/entronad/graphic/issues/209, the major version should change.

I have retracted v1.1.0 and republished as v2.0.0
