### ISSUE TITLE
big data

### ISSUE THREAD

**Issue by m2faridi** [entronad/graphic#3]
this lib good for big data?
10k items

**Comment by entronad** [comment]
As I have tested:
For line/area, more than 10k (even up to 100k) data items is quite OK;
But for point/interval, more than 1k, the rendering can be significantly slow.

This is because for line/area, only one polyline/polygon RenderShape object is created, no matter how many data items there are.
But for point/interval, we have to create RenderShape objects for all data items.

I think this is enough for most Flutter apps, because for big data we always use a line/area chart.
No designer allows a chart crowded with 10k bars :)

**Comment by entronad** [comment]
We investigated the rendering process and find that the _sort() function in group.addShape() is the main time consumming part, especially for big data.
It is not a nessasary step when composing chart renderer nodes, so we removed it.
This greatly reduced the rendering time, now a chart with 10k points can be easilly rendered.
This uptate is in version 0.3.0
