### ISSUE TITLE
Border color and border width for IntervalElements

### ISSUE THREAD

**Issue by dJani97** [entronad/graphic#57]
Is it possible to mimic the following configuration from e-charts?

    itemStyle: {
      borderColor: '#fff',
      borderWidth: 2
    },

This adds a gap between the slices of the pie.

Example:
 [https://echarts.apache.org/examples/en/editor.html?c=pie-borderRadius](https://echarts.apache.org/examples/en/editor.html?c=pie-borderRadius)

![image](https://user-images.githubusercontent.com/22769564/156259522-94dc5604-6d91-474f-8b75-95e67ad0bb6d.png)

Another use of the same feature:

    itemStyle: {
      borderColor: '#000',
      borderWidth: 1
    },

![image](https://user-images.githubusercontent.com/22769564/156259917-7b87cc7c-bebf-443f-a2bf-f96fd157b746.png)

A similar effect to the second example can be achieved by layering two IntervalElements on top of each other, the bottom one being slightly bigger and painted to black. But this is a workaround and it kinda looks messy, the borders are not exactly even on all sides. I did something like that in my example here: https://github.com/entronad/graphic/issues/56

You can see the "borders" thinning around the end:

![image](https://user-images.githubusercontent.com/22769564/156267133-89c84e90-04c0-4098-b05f-ec678d5565f0.png)

**Comment by entronad** [comment]
The best solution for your case is to custom your own Shape class.

There are some reasons for that built-in Shapes don't have borders.

Firstly, in the dart painting APIs, shapes have either `stroke` or `fill` painting style, not "body and border" like the Web Canvas, so a bordered shape involves multiple shapes, that may harm the performance.

Secondly, "border" is not a single property, it involves width, color, gradient, dash pattern, stroke cap... that will make the Shape's properties very verbose.

Finally, is border really a good idea for data visualizations graphics, or for Flutter apps? I have seldomly seen data viz theories or works involve shape borders. And in Material Design shadows are more common than borders.

So we don't paint borders in built-in shapes.

But if you really need borders, there is a good way. One of the most important ideas of Graphic is that you can custom anything with your own Shape class.

For your case, instead of using the default `RectShape`, extends your own class from the base `IntervalShape`, and override the `renderGroup` class. You can refer to the built-in `RectShape` below.

As I can see, you only need to render a additional border figure above the original shape with the same path but `stroke` painting style in the `_renderSector`, it's easy with the `renderBasicItem` function:

https://github.com/entronad/graphic/blob/f808963a7001f54b48b95e538501d6e67a4ab93d/lib/src/shape/interval.dart#L389

**Comment by dJani97** [comment]
Thank you for the detailed guide, I really appreciate it!

I've added the `borderWidth` and `borderColor` properties to my own extension of `RectShape`, and also added an extra `renderBasicItem()` call using these properties:

```dart
rst.addAll(renderBasicItem(
  path,
  item.copyWith(color: borderColor),
  true,
  borderWidth,
  coord.region,
));
```

Here's my rough implementation, in case anyone else needs it: [BorderedRectShape for graphic](https://gist.github.com/dJani97/aed1dd8b2adc7ddac6447db2d56bd483)

It works well:

![image](https://user-images.githubusercontent.com/22769564/157189472-d4080c93-63df-46a5-9fe4-e0718fa9472c.png)

![image](https://user-images.githubusercontent.com/22769564/157189388-8189e91c-1bca-4806-98f8-1a24cccd47a4.png)

![image](https://user-images.githubusercontent.com/22769564/157189740-e2d172ed-a56a-4f68-a621-0c4ffce7109d.png)

**Comment by dJani97** [comment]
@entronad 

Since the `_renderSector` method is private, my implementation involves overriding the entire `renderGroup` method from the `RectShape` class. So it will be difficult to maintain.

If an official implementation would make it into the library, I'd really glad. For example, an optional properties class could be added to the `RectShape` constructor. This would not _"make the Shape's properties very verbose"_, and wouldn't break or slow down any existing code. Although it does not play well with the existing `borderRadius` constructor parameter. Maybe `borderRadius` could be deprecated and incorporated into this new class? I'm just ideating.

```dart
class BorderProperties {
  final double width;
  final Color color;
}
```
```dart
RectShape({
  this.histogram = false,
  this.labelPosition = 1,
  this.borderRadius,
  this.borderProperties,
});
```
And then something like this:

```dart
if (this.borderProperties != null) {
  rst.addAll(renderBasicItem(
    path,
    item.copyWith(color: borderProperties.color),
    true,
    borderProperties.width,
    coord.region,
  ));
}
```

Since it would be an optional parameter, it wouldn't cripple rendering performance unless it's being used.

**Comment by entronad** [comment]
Thanks, we are very glad if you make a PR.

Your idea of implementation seems quite good.

Only a little advice about the API. the property name we prefer just to be `RectShape.border`, XXProperties seems redundant. And you don't need to define a new class, a built-in Flutter class: [BorderSide](https://api.flutter.dev/flutter/painting/BorderSide-class.html) has all information you need(it even has default styles). One of Graphic's principle is prefer to use Dart/Flutter built-in classes.

Then this property looks like:
```
BorderSide? border;
```
the render condition is `border != null && border.style != BorderStyle.none`.

**Comment by entronad** [comment]
@dJani97 
Is there any progress about the PR?
