### ISSUE TITLE
Allow plotting of null values

### ISSUE THREAD

**Issue by bernardobelchior** [entronad/graphic#66]
**Given:**

* A data list with null values
* A chart with line and point elements
* A scale with the ticks set

**Then:**

* Expected:
  * When the values are null, the chart does not render points and joins the line with the next point
* Reality:
  * It crashes

What I'm trying to achieve:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/12778398/158839256-4a22ccd6-d702-4f23-b73a-1578ea3d38e2.png">

Notice how there isn't an orange point below the green point at approximately (8, 8).

### My attempts

I haven't found a way of doing this "the right way", i.e., by returning `null` values from the accessor.

I've found a workaround (while changing the lib's code) to plot null values by returning `double.nan` from the accessor. This breaks in the Wilkinson algorithm, but I've bypassed it by hardcoding the ticks.

I've then made two modifications to the `CircleShape` and `BasicLineShape` to allow points with position `NaN`:
* In `BasicLineShape` I have commented the else part of [these lines](https://github.com/entronad/graphic/blob/main/lib/src/shape/line.dart#L80-L83).
* In `CircleShape`, I have added between [these lines](https://github.com/entronad/graphic/blob/main/lib/src/shape/point.dart#L109-L110) the following code: `if(!point.dx.isFinite || !point.dy.isFinite) { return Path(); }`

You can check the changes and a working example in this [draft PR](https://github.com/entronad/graphic/pull/65). It is still in draft since it is very rough. If you think this is something worth exploring, I wouldn't mind cleaning it up and creating a proper PR.

**Comment by entronad** [comment]
In Graphic, there are two status of data: the original datum and the tuple. The original datum can be any type, but the tuple is a map, and its values can only be num, String, or DateTime. the Variable.accessor defines how to get these values.

The current solution is: tuple values don't allow null, for functional elements(point, line, area, interval), y values allow double.nan, but x values don't.

There are some reasons for it:
1. data visualization is the last step of data pipeline. Data cleaning should be down before it. It's better to pass "proper" tuples to the chart. So if you really want to "skip" these null values, the best way is to filter them before passing to the chart.
2. Yet there are cases that people want to show there are "bad" values, like in monitoring apps. so if a double.nan is passed to a line, there will be a break to emphasize that.
3. Why allow double.nan, not null? because Dart is now a null-safe language, null or num? should be best avoided.

**Comment by bernardobelchior** [comment]
You make a good point. I'll try to better understand if this behavior I'm proposing makes sense with regards to the Grammar of Graphics.

I'll create a separate issue, though, since it seems that the `Point` primitive does not correctly handle `double.nan` values:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: 'dart:ui/painting.dart': Failed assertion: line 31 pos 10: '<optimized out>': Rect argument contained a NaN value.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      _rectIsValid (dart:ui/painting.dart:31:10)
#3      Path.addOval (dart:ui/painting.dart:2464:12)
#4      CircleShape.path (package:graphic/src/shape/point.dart:112:9)
#5      PointShapeBase.renderItem (package:graphic/src/shape/point.dart:69:23)
#6      PointShape.renderGroup (package:graphic/src/shape/point.dart:28:29)
#7      ElementRenderOp.render (package:graphic/src/geom/element.dart:235:46)
```

**Comment by bernardobelchior** [comment]
Hey! I've managed to do this by extending the `BasicLineShape`. This, with the `Point` issue fixed, should be enough to allow me to do what I wanted to do without further changes to the library. As such, I'll close this issue.

Thank you for your help! This library has an amazing API, by the way. Everything seems customizable and it feels like we can do whatever we want with it, great work!

**Comment by entronad** [comment]
Thanks for your praise! If convenient, please introduce this lib to the dev community in your country.
