### ISSUE TITLE
Zooming individual y-axis

### ISSUE THREAD

**Issue by LucaCras** [entronad/graphic#74]
Hi there, I've recently found this package, and it looks amazing! But I have a question regarding zooming. I have found out that we can zoom based on the range updaters, but for my use case, I need to have 2 y-axes (one on the left, and one on the right),  adding the second axis was pretty straightforward, but how can I specifically zoom one axis at a time in stead of both at the same time (which is what happens now)

**Comment by LucaCras** [comment]
Similar to this feature from vega lite: https://vega.github.io/vega-lite/docs/layer.html#combined-scales-and-guides

**Comment by LucaCras** [comment]
@entronad, would the best way maybe be to add the ability to specify multiple coords (with names?), and then allow each scale to specify a corresponding coord system, thereby allowing different coord systems to have different range updaters and achieving independence?

If so I can look to make a PR for this :)

**Comment by entronad** [comment]
There are some concepts in a chart:
- scale: indicates how tuple value converts to `[0, 1]`
- region: it is always the chart size without padding. It is the visual limits of the coordinate.
- coordinate: it converts values in `[0, 1]` to pixel position. Its boundary may not be the region.

The ratio of the coordinate boundary to the region is called ranges. the updater for scale gesture is applied to ranges, not scales, because scale is a totally abstract concept, but range is a bridge between abstract and perception.

So if there are multiple scales in one dim in a coordinate, it is not possible to zoom only part of them, because the zooming always affects the whole coordinate. And a chart can only have one coordinate.

In fact, this is deliberate. all graphics in a visual region should be related and keep the graphic ratio consist, so they should in a common coordinate and the ratio between scales is locked.

But if you realy need to make this partial changes, there is a workaround (a little troublesome), That is to make two chart widgets and stack them, one for static scales and one for zoomable scales.
